language: node_js
cache: yarn
node_js:
- '8.11.3'
before_script:
  - npm install
script: 
  - yarn run test:CI
  - npm run prebuild:CI
  - npm run build:CI
after_success:
  - yarn run test:cover:CI
env:
deploy:
  skip_cleanup: true
  before_deploy: 
    - "echo 'Starting build for repo'"
  after_deploy: "echo 'Build for repo completed!'"